version: '2'
services:
  reports:
    image: denvazh/gatling
    environment:
    - TZ=America/Sao_Paulo
    volumes: 
    - ./cache/gatling:/opt/gatling/results
    - ./gatling:/opt/gatling/conf:ro
    command: --reports-only /opt/gatling/results
    logging:
      options:
        max-size: 1m