version: '2'
services:
  gatling:
    image: maven:alpine
    environment:
    - TZ=America/Sao_Paulo
    volumes:
    - ./cache/repository:/root/.m2/repository
    - ./cache/gatling:/results
    - ..:/gatling
    - ./gatling/gatling.conf:/gatling/src/test/resources/gatling.conf:ro
    - ~/.m2/settings.xml:/root/.m2/settings.xml:ro
    working_dir: /gatling
    entrypoint: mvn clean test -Dgatling.resultsFolder=/results -Dgatling.noReports=false
    command: -Dgatling.simulationClass=br.com.nomeCliente.nomeApi.simulation.nomeRota
    environment:
    - MAVEN_OPTS=-Xms1g -Xmx1g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false
    links:
    - influxdb
    - grafana
    logging:
      options:
        max-size: 1m

  influxdb:
    image: influxdb:alpine
    environment:
    - TZ=America/Sao_Paulo
    volumes:
    - ./cache/influxdb/data:/var/lib/influxdb
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    expose:
    - 8083/tcp
    - 8086/tcp
    - 2003/tcp
    logging:
      options:
        max-size: 1m

  grafana:
    image: grafana/grafana
    environment:
    - TZ=America/Sao_Paulo
    environment:
    - INFLUXDB_NAME=gatling
    - INFLUXDB_HOST=influxdb
    volumes:
    #- ./grafana/run.sh:/run.sh:ro
    - ./grafana/data:/var/lib/grafana
    ports:
    - "8081:3000"
    links:
    - influxdb
    logging:
      options:
        max-size: 1m
